queue_rules:
  - name: default
    conditions:
      - "check-success=test / test"
pull_request_rules:
  - name: automatic merge for dependency bots
    conditions:
      - or:
          - author=tna-da-bot
          - author=dependabot[bot]
      - "check-success=test / test"
      - or:
          - files=build.sbt
          - files~=^(!?project/)
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependency bot updates
      queue:
        name: default
merge_queue:
  max_parallel_checks: 1
